// File generated by FlutterFire CLI.
// Contains default Firebase options for your app.
// For details on how to use this file, see: https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for your app.
///
/// Real Firebase configuration values from the Firebase console.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        // No official Firebase support for Windows yet
        return web; // Fallback to web config for Windows
      case TargetPlatform.linux:
        // No official Firebase support for Linux yet
        return web; // Fallback to web config for Linux
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Updated Firebase config values from your google-services.json file
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_GOOGLE_API_KEY_HERE',
    appId: '1:264217952252:web:07c2c349c8202ef85abc79',
    messagingSenderId: '264217952252',
    projectId: 'menstralapp',
    authDomain: 'menstralapp.firebaseapp.com',
    storageBucket: 'menstralapp.appspot.com', // Corrected bucket URL
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_GOOGLE_API_KEY_HERE',
    appId: '1:264217952252:android:07c2c349c8202ef85abc79',
    messagingSenderId: '264217952252',
    projectId: 'menstralapp',
    storageBucket: 'menstralapp.appspot.com', // Corrected bucket URL
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_GOOGLE_API_KEY_HERE',
    appId: '1:264217952252:ios:07c2c349c8202ef85abc79',
    messagingSenderId: '264217952252',
    projectId: 'menstralapp',
    storageBucket: 'menstralapp.appspot.com', // Corrected bucket URL
    // If you don't have actual values, omit these values or use the web values
    // iosClientId: 'YOUR_IOS_CLIENT_ID.apps.googleusercontent.com',
    // iosBundleId: 'com.example.menstralapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_GOOGLE_API_KEY_HERE',
    appId: '1:264217952252:ios:07c2c349c8202ef85abc79',
    messagingSenderId: '264217952252',
    projectId: 'menstralapp',
    storageBucket: 'menstralapp.appspot.com', // Corrected bucket URL
    // If you don't have actual values, omit these values or use the web values
    // iosClientId: 'YOUR_IOS_CLIENT_ID.apps.googleusercontent.com',
    // iosBundleId: 'com.example.menstralapp',
  );
}
